import { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header/page";

export const metadata: Metadata = {
  title: {
    default: "This will display for all",
    template: "%s | Page",
  },
  description: "Generated by Next.js",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <title>Next.js App</title>
      </head>
      <body>
        <Header />

        <main>{children}</main>

        <footer className="footer">
          <h2>Next.js Footer</h2>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
