import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Blog Page",
  },
  description: "Generated by Next.js",
};

export default function Blog() {
  return <h1>Welcome Blog</h1>;
}
